### ISSUE TITLE
UserModel 的arr的属性里不能添加FatherModel 作为元素吗

### ISSUE THREAD

**Issue by ClockCake** [onepiec/TLBaseModel#1]
数组里不能添加Mode里吗

**Comment by onepiec** [comment]
我刚试了下，可以添加的

**Comment by ClockCake** [comment]
> 我刚试了下，可以添加的
  我用下面的代码测试了一下，添加是可以添加的，但是在后面newModel 里取出来的时候提醒解挡失败，然后存的值都为nil 了。。
![Jietu20190618-210653](https://user-images.githubusercontent.com/16621692/59736097-1a995f80-920d-11e9-8ff5-fd9de4713ef8.jpg)


    FoodModel *foodModelA = [FoodModel new];
    foodModelA.foodName = @"青菜";
    foodModelA.foodImageName = @"青菜图";
    
    
    FoodModel *foodModelB = [FoodModel new];
    foodModelB.foodName = @"红烧肉";
    foodModelB.foodImageName = @"红烧肉图";
    
    RootModel *rootModel = [RootModel sharedInstance:UserKey0];
    rootModel.name = @"西门吹雪";
    rootModel.sex = @"男";
    rootModel.foods = [NSArray arrayWithObjects:foodModelA,foodModelB ,nil];
    
    [RootModel saveData:UserKey0];
    
    
    RootModel *newModel = [RootModel sharedInstance:UserKey0];
    NSLog(@"---%@----",newModel);
    NSLog(@"----%lu----",newModel.foods.count);

**Comment by onepiec** [comment]
你好，已经优化了
问题参考：http://www.itkeyword.com/doc/0622359176703898379/xpc-not-registering-classes-correctly-for-collection
